name: Semgrep

on:
  push:
    branches:
      - main
      - master
      - v1.0.1
  schedule:
    - cron: '0 0 * * 0'

jobs:
  semgrep:
    if: ${{ secrets.SEMGREP_APP_TOKEN != '' }}
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
